on:
  workflow_dispatch:
    inputs: {}

jobs:
  locale-detect:
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: pip install -r requirements.txt

    - name: detect locales from python
      run: python detect-locale.py
