on:
  workflow_dispatch:
    inputs: {}

jobs:
  locale-detect:
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64

    steps:
    - uses: actions/checkout@v1

    - name: install pywin32
      run: pip install pywin32

    - name: detect locales from python
      shell: python
      run: |
        import pywin32
